name: Setup environment
description: Sets up some basic components of the environment
inputs:
  ansible:
    description: Install Ansible as well
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3"
    - name: Setup pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - name: Install Pip and tox
      shell: bash
      run: |
        set -exo pipefail
        python3 -m pip install -U pip
        pip install -U wheel
        pip install -U tox
    - name: Install Ansible
      if: inputs.ansible == 'true'
      shell: bash
      run: |
        set -exo pipefail
        pip install -U ansible
        ansible-galaxy collection install -r ansible/requirements.yml
