name: Install Packer
description: Installs the packerio executable and its attendant tools to /usr/local/bin
  for Ubuntu hosts
inputs:
  version:
    description: Version of Packer to install
    required: true
    default: "1.8.0"
  pup_version:
    description: Version of Pup to install
    required: true
    default: "v0.4.0"
runs:
  using: composite
  steps:
    - shell: bash
      if: runner.os == 'Linux'
      run: |
        set -exo pipefail
        # Install virtualbox
        sudo apt-get update
        #sudo apt-get install -y software-properties-common
        #Download
        #curl https://www.virtualbox.org/download/oracle_vbox_2016.asc -O oracle_vbox_2016.gpg
        #curl https://www.virtualbox.org/download/oracle_vbox.asc -O oracle_vbox.gpg
        ##Install on system
        #sudo install -o root -g root -m 644 oracle_vbox_2016.gpg /etc/apt/trusted.gpg.d/
        #sudo install -o root -g root -m 644 oracle_vbox.gpg /etc/apt/trusted.gpg.d/
        #echo "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
        #sudo apt-get update
        #sudo apt-get install -y virtualbox-6.1
        # Install QEmu, etc
        sudo apt-get install -y unzip python3-{virtualenv,yaml} cloud-utils qemu-system-{x86,ppc}
        # Install packer.io
        curl -O https://releases.hashicorp.com/packer/${{ inputs.version }}/packer_${{ inputs.version }}_linux_amd64.zip
        unzip -o packer_${{ inputs.version }}_linux_amd64.zip -d /usr/local/bin
        chmod +x /usr/local/bin/packer
        # Install pup
        curl -L -o pup.zip "https://github.com/ericchiang/pup/releases/download/${{ inputs.pup_version }}/pup_${{ inputs.pup_version }}_linux_amd64.zip"
        sudo unzip pup.zip -d /usr/local/bin
        sudo chmod +x /usr/local/bin/pup
    - shell: bash
      if: runner.os == 'macOS'
      run: |
        set -exo pipefail
        brew install qemu
        brew install pup
        # Packer is already installed
