- name: Update all the things
  become: true
  ansible.builtin.package:  # noqa package-latest
    name: "*"
    state: latest
    update_cache: true
  register: _update_all
  retries: 3
  until: _update_all is success
