- name: read variables
  include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts.distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
  when: item is file

- name: install vmware related packages
  become: true
  package:
    name: "{{ vmware_packages }}"
    state: present

- name: modern systems
  import_tasks: has_package.yml
  when: >-
    ansible_distribution_name == 'fedora' or
    (ansible_distribution_name == 'debian' and
    ansible_distribution_major_version > '8')

- name: legacy builds
  import_tasks: legacy.yml
  when: >-
    (ansible_distribution_name == 'debian' and
    ansible_distribution_major_version <= '8')
