- name: read variables
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts.distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
  when: item is file

- name: install vmware related packages
  become: true
  ansible.builtin.package:
    name: "{{ vmware_packages }}"
    state: present

- name: modern systems
  ansible.builtin.import_tasks: has_package.yml
  when: >-
    ansible_facts.distribution == 'fedora' or
    (ansible_facts.distribution == 'debian' and
    ansible_facts.distribution_major_version > 8)

- name: legacy builds
  ansible.builtin.import_tasks: legacy.yml
  when:
    - ansible_facts.distribution == 'debian'
    - ansible_facts.distribution_major_version <= '8'
