dependency:
  name: galaxy
  options:
    role-file: ../requirements.yml  # relative to the role dir
    requirements-file: ../requirements.yml
provisioner:
  name: ansible
  playbooks:  # These paths are relative to scenario dir
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
    cleanup: ../shared/cleanup.yml
  config_options:
    defaults:
      stdout_callback: yaml
      force_color: true
      remote_tmp: /tmp/${USER}/ansible
verifier:
  name: ansible
  additional_files_or_dirs:
    - ../../shared/tests  # relative to the scenario tests dir
