- name: install guest additions
  hosts: default
  vars:
    ansible_remote_tmp: /tmp
  pre_tasks:
    - name: Pause for a moment in case we need cloud-init to finish
      ansible.builtin.pause:
        seconds: 20
  roles:
    - role: latest
    - role: devroles.system.epel
    - role: virtualbox
      when: packer_builder_type == 'virtualbox-iso'
    - role: vmware
      when: packer_builder_type == 'vmware-iso'
    - role: qemu
      when: packer_builder_type == 'qemu'
    - role: init
    - role: locale
    - role: vagrant
    - role: cleanup
