- name: install guest additions
  hosts: default
  pre_tasks:
    - name: update all the things
      become: true
      ansible.builtin.package:  # noqa package-latest
        name: "*"
        state: latest
      when: ansible_facts.pkg_mgr not in ['atomic_container']

    - name: update atomic things
      become: true
      ansible.builtin.command: rpm-ostree upgrade
      when: ansible_facts.pkg_mgr in ['atomic_container']
      changed_when: false
  roles:
    - role: virtualbox
      when: packer_builder_type == 'virtualbox-iso'
    - role: vmware
      when: packer_builder_type == 'vmware-iso'
    - role: init
    - role: devroles.system.epel
    - role: locale
    - role: vagrant
    - role: cleanup
