- name: install build deps for virtualbox addons
  become: true
  ansible.builtin.package:
    name: "{{ virtualbox_packages }}"
    state: present

- name: start services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ virtualbox_services }}"

- name: mount iso file
  become: true
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  loop:
    - mount -o loop,ro {{ ansible_user_dir }}/VBoxGuestAdditions.iso /mnt
    - /mnt/VBoxLinuxAdditions.run
    - umount /mnt

- name: remove iso
  ansible.builtin.file:
    name: "{{ ansible_user_dir }}/VBoxGuestAdditions.iso"
    state: absent
