- name: remove unnecessesary packages
  become: true
  ansible.builtin.package:
    name:
      - make
      - perl
      - gcc
      - kernel-devel
      - kernel-headers
      - bzip2
      - epel-release
    state: absent
