name: Perform formatting and sanity checks

"on":
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Packer templates are reasonable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Packer
        uses: ./.github/actions/install_packer
      - name: Run validate check
        run: |
          set -exo pipefail
          packer init sources
          for vars in $(find distros/ -name '*.pkrvars.hcl*'); do
            if [[ "${vars}" == *.sh ]]; then
              "./${vars}"
              vars=${vars%.sh}
            fi
            packer validate -except=upload -var-file=${vars} sources/
          done
      - name: Run Packer format check
        run: packer fmt -check $(git ls-files | grep -E -e '.hcl$')

  lint:
    name: Lint shell code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install shellcheck
        run: |
          shellcheck --version
          shellcheck $(find . -name '*.sh')
