name: Perform formatting and sanity checks

"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Packer templates are reasonable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Packer
        uses: ./.github/actions/install_packer
      - name: Run syntax check
        run: |
          set -exo pipefail
          packer init sources
          for vars in $(find distros/ -name '*.pkrvars.hcl'); do
            if [[ "${vars}" == *.sh ]]; then
              "./${vars}"
              vars=${vars%.sh}
            fi
            packer validate -except=upload -var-file=${vars} sources/
          done

  lint:
    name: Lint shell code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          for script in $(find . -name '*.sh'); do
            shellcheck "${script}"
          done
