name: Test the components of it

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packer
        uses: ./.github/actions/install_packer/
      - name: Run syntax check
        run: |
          set -exo pipefail
          for vars in distros/*; do
            ~/bin/packerio validate -except=upload -var-file=${vars} sources/
          done
